src/beans/UserManagement.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class UserManagement implements Serializable{
	private static final long serialVersionUID = 1L;

	private int id;
	private int user_id;
	private String name;
	private int branch_id;
	private int position_id;
	private int is_stopped;
	private Date created_date;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUser_id() {
		return user_id;
	}
	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getBranch_id() {
		return branch_id;
	}
	public void setBranch_id(int branch_id) {
		this.branch_id = branch_id;
	}
	public int getPosition_id() {
		return position_id;
	}
	public void setPosition_id(int position_id) {
		this.position_id = position_id;
	}
	public Date getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Date created_date) {
		this.created_date = created_date;
	}
	public int getIs_stopped() {
		return is_stopped;
	}
	public void setIs_stopped(int is_stopped) {
		this.is_stopped = is_stopped;
	}


}

src/beans/UserNewPublish.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class UserNewPublish implements Serializable{
	private static final long serialVersionUID = 1L;

	private int id;
	private int user_id;
	private String name;
	private int branch_id;
	private int position_id;
	private String title;
	private String text;
	private String category;
	private Date created_date;
    public String searchCategory;
    public String firstDate;
    public String finalDate;


	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getBranch_id() {
		return branch_id;
	}
	public void setBranch_id(int branch_id) {
		this.branch_id = branch_id;
	}
	public int getPosition_id() {
		return position_id;
	}
	public void setPosition_id(int position_id) {
		this.position_id = position_id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Date getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Date created_date) {
		this.created_date = created_date;
	}
	public int getUserid() {
		return user_id;
	}
	public void setUserid(int user_id) {
		this.user_id = user_id;
	}
	public String getSearchCategory() {
		return searchCategory;
	}
	public void setSearchCategory(String searchCategory) {
		this.searchCategory = searchCategory;
	}
	public String getFirstDate() {
		return firstDate;
	}
	public void setFirstDate(String firstDate) {
		this.firstDate = firstDate;
	}
	public String getFinalDate() {
		return finalDate;
	}
	public void setFinalDate(String finalDate) {
		this.finalDate = finalDate;
	}
}

src/controller/HomeServlet.java
package controller;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import beans.UserComment;
import beans.UserNewPublish;
import service.CommentService;
import service.NewPublishService;

/**
 * Servlet implementation class HomeServlet
 */
@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		String searchCategory = request.getParameter("searchCategory");
		String firstDate = request.getParameter("firstDate");
		String finalDate = request.getParameter("finalDate");

		if(firstDate == null || (StringUtils.isBlank(firstDate) == true)){
			firstDate = "2018-05-01";
		}else{
			request.setAttribute("firstDate", firstDate);
		}
		if(finalDate == null || (StringUtils.isBlank(finalDate) == true)){
//			finalDate = "2018-05-31";
			//今日の日付を取得する処理
			Date today = new Date();
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
			finalDate = sdf.format(today);
		}else{
			request.setAttribute("finalDate", finalDate);
		}
		//カテゴリーが入力されていたら、保持する処理
		if(searchCategory != null && (StringUtils.isBlank(searchCategory) == false)){
			request.setAttribute("searchCategory", searchCategory);
		}
		//if(searchCategory == null && firstDate == null && finalDate == null) {

		//}

	/*	List<String> searchList = new ArrayList<String>();
		searchList.add(searchCategory);
		searchList.add(firstDate);
		searchList.add(finalDate);

		request.setAttribute(finalDate, searchList);*/



		//System.out.println(firstDate);

//		if (StringUtils.isBlank(title) == true) {
//			 messageList.add("タイトルを入力してください");


//		 }


		 //投稿表示
		 List<UserNewPublish> newPublishes  = new NewPublishService().getMessage(firstDate, finalDate,searchCategory);
		 request.setAttribute("newPublishes",  newPublishes);


		 //コメント表示
		 List<UserComment> comments = new CommentService().getComment();
		 request.setAttribute("comments",  comments);
		 request.getRequestDispatcher("/home.jsp").forward(request, response);
	}
/*

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("/home.jsp").forward(request, response);
	}*/
}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.LoginService;

/**
 * Servlet implementation class LoginServlet
 */
@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	 protected void doGet(HttpServletRequest request,
	    		HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("login.jsp").forward(request, response);
		}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
		//JSPから入力された値を受け取る
		String login_id = request.getParameter("login_id");
	    String password = request.getParameter("password");

       // System.out.println(login_id);

        LoginService loginService = new LoginService();
        User user = loginService.login(login_id, password);

        HttpSession session = request.getSession();
        User loginUser = getLoginUser(request);

        if (user != null) {
        	session.setAttribute("loginUser", user);

            if(user.is_stopped != 0) {
            	//ユーザーが停止されていた時の処理
            	List<String> messages = new ArrayList<String>();
        		messages.add("ログインに失敗しました");
        		session.setAttribute("errorMessages", messages);
        		request.setAttribute("loginuser",loginUser);
        		request.getRequestDispatcher("login.jsp").forward(request, response);
        		return;
        	}
        } else {
    		List<String> messages = new ArrayList<String>();
    		messages.add("ログインに失敗しました");
    		session.setAttribute("errorMessages", messages);
    		request.setAttribute("loginuser",loginUser);
    		request.getRequestDispatcher("login.jsp").forward(request, response);
    		return;
        }
        response.sendRedirect("./");
	}
	private User getLoginUser(HttpServletRequest request)
		throws IOException, ServletException {

		User loginUser = new User();
		loginUser.setLogin_id(request.getParameter("login_id"));
		request.setAttribute("loginuser",loginUser);
		return loginUser;
	}
}

src/controller/SettingsServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Branch;
import beans.Position;
import beans.User;
import exception.NoRowsUpdatedRuntimeException;
import service.UserService;

/**
 * Servlet implementation class SettingsServlet
 */
@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
		//支店、部署などをプルダウンに自動表示
		List<Branch> branchList = new UserService().getBranch();
		request.setAttribute("branchList",branchList);

		List<Position> positionList = new UserService().getPosition();
		request.setAttribute("positionList",positionList);

		//数字以外は不正
		List<String> messages = new ArrayList<String>();
		if(!String.valueOf(request.getParameter("id")).matches("^[0-9]+$") ) {
			messages.add("不正なアクセスです");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("userManagement");
			return;
		}
		//HttpSession session = request.getSession();
//	        User users = (User) session.getAttribute("users");
		//ユーザー編集

		//ユーザー編集画面の表示 空は不正
		int userId = Integer.parseInt(request.getParameter("id"));
		User editUser = new UserService().getUser(userId);
		if(editUser == null) {
			messages.add("不正なアクセスです");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("userManagement");
			return;
		}
		request.setAttribute("editUser", editUser);
		request.setAttribute("before_id", editUser.getLogin_id());
		request.getRequestDispatcher("settings.jsp").forward(request, response);
	}
	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		//支店、部署などをプルダウンに自動表示の保持
		List<Branch> branchList = new UserService().getBranch();
		request.setAttribute("branchList",branchList);

		List<Position> positionList = new UserService().getPosition();
		request.setAttribute("positionList",positionList);


		//ユーザー設定変更
		List<String> users = new ArrayList<String>();
		HttpSession session = request.getSession();
	    User editUser = getEditUser(request);
		session.setAttribute("editUser", editUser);
		/*String password1 = request.getParameter("password1");
		String password2 = request.getParameter("password2");
		if(StringUtils.isEmpty(password1) && StringUtils.isEmpty(password2)) {
	        session.setAttribute("password1",password1);
		}*/

		//バリデーションOKだったら、更新する処理
		if (isValid(request, users) == true) {
			try {
				new UserService().update(editUser);

			} catch (NoRowsUpdatedRuntimeException e) {
				session.setAttribute("errorMessages", users);
	            request.setAttribute("editUser", editUser);
	            response.sendRedirect("settings");
	            return;
	        }
	            session.setAttribute("users", editUser);
	            response.sendRedirect("userManagement");
	    } else {
	    	request.setAttribute("before_id",request.getParameter("before_id"));
	    	session.setAttribute("errorMessages", users);
	        request.setAttribute("editUser", editUser);
	        request.getRequestDispatcher("settings.jsp").forward(request, response);
	    }

	}
	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {
		//ユーザー設定変更用の要素をJSPから受け取る
		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setName(request.getParameter("name"));
		editUser.setPassword(request.getParameter("password1"));
		editUser.setBranch_id(Integer.parseInt(request.getParameter("branch")));
		editUser.setPosition_id(Integer.parseInt(request.getParameter("position")));
		editUser.setLogin_id(request.getParameter("login_id"));
		return editUser;

	}
	private boolean isValid(HttpServletRequest request, List<String> users)
			throws IOException, ServletException {

		String name = request.getParameter("name");
		String before_id = request.getParameter("before_id");
		String login_id = request.getParameter("login_id");
		String password1 = request.getParameter("password1");
		String password2 = request.getParameter("password2");
		int positionId = Integer.parseInt(request.getParameter("position"));
		int branchId = Integer.parseInt(request.getParameter("branch"));;
		//request.setAttribute("password1",password1);

		User userList = new UserService().getLoginId(login_id);
		request.setAttribute("loginIdList",userList);
//		User user = new UserService().getUser(userId);
		User editUser = getEditUser(request);

		if(StringUtils.isBlank(name) == true) {
	    	 users.add("名称を入力してください");
	     } else if( name.length() >= 10) {
	    	 users.add("名称は10文字以下で入力してください");
	     }
	     if(StringUtils.isBlank(login_id) == true) {
	    	 users.add("ログインIDを入力してください");
	     } else if(!login_id.matches("^[0-9a-zA-Z]{6,20}$")) {
	    	 users.add("ログインIDは半角英数字6文字以上20文字以下で入力してください");
		 }
        if(!before_id.equals(login_id)){
        	if(userList != null && editUser.getId() != userList.getId()){
        		users.add("そのログインIDは使用できません");
        	}
        }


       /* if(StringUtils.isBlank(password1) == true) {
        	users.add("パスワードを入力してください");
        }
        if(StringUtils.isBlank(password2) == true) {
 	        users.add("確認用パスワードを入力してください");*/
        //}


        if(StringUtils.isBlank(password1) != true &&
	    		 !password1.matches("^[a-zA-Z0-9\\p{Punct}]{6,20}$")) {
	    	 users.add("パスワードは半角英数字記号6文字以上20文字以下で入力してください");
	    } else if(!StringUtils.isBlank(password1) && !password1.matches(password2) || !StringUtils.isBlank(password2) && !password2.matches(password1)) {
	        	users.add("パスワードと確認パスワードが一致していません");
	    } else
        if(!StringUtils.isEmpty(password1) && !StringUtils.isEmpty(password2)) {
        	if(StringUtils.isBlank(password1) && StringUtils.isBlank(password2)) {
        	users.add("パスワードは空白で入力することはできません");
        	}
        } else if(!StringUtils.isEmpty(password1) || !StringUtils.isEmpty(password2)) {
        	if(StringUtils.isBlank(password1) || StringUtils.isBlank(password2)) {
        	users.add("パスワードは空白で入力することはできません");
        	}
        }

	     if(branchId == 0 && positionId != 0) {
	    	 users.add("支店を選択してください");
	     }
	     if(branchId != 0 && positionId == 0) {
	    	 users.add("部署･役職を選択してください");
	     }
	     if(branchId == 0 && positionId == 0) {
	    	 users.add("支店と部署･役職を選択してください");
	     }
        if(branchId != 1 && (positionId == 1 || positionId == 2) == true) {
        	users.add("支店と部署･役職の組み合わせが不正です");
        }
	     if(branchId == 1 && positionId == 3) {
	    	 users.add("支店と部署･役職の組み合わせが不正です");
	     }
	  /*  if(!password1.matches("{6,20}""^[a-zA-Z0-9\-\\.\\/\\^\\@\]{6,20}$")){
	    	users.add("パスワードは6文字以上20文字以下で登録してください");
	    }*/

        /*if(password1 != password2 == true) {
        	users.add("パスワードと確認パスワードが一致していません。");
        }*/
        if (users.size() == 0) {
            return true;
        } else {
            return false;
	    }
	}
}

src/controller/UserManagementServlet.java
package controller;


import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.User;
import service.UserManagementService;

@WebServlet(urlPatterns = { "/userManagement" })
public class UserManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		//全ユーザー情報が入ったユーザーリストを保持し、serviceに渡す
		List<User> userList  = new UserManagementService().getUsers();
		request.setAttribute("userList", userList);
		request.getRequestDispatcher("userManagement.jsp").forward(request, response);
	}

// 	private boolean isValid(HttpServletRequest request, List<User> toUserList) {
//
// 		 String name = request.getParameter("Name");
//		 String id = request.getParameter("Id");
//
//		 return true;
// 	}
/* 	@Override
 	protected void doPost(HttpServletRequest request,
        HttpServletResponse response) throws IOException, ServletException {

		 request.getRequestDispatcher("userManagement.jsp").forward(request, response);
 	}*/
}

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>社内掲示板</title>
</head>
<head>
    <link href="./css/home.css" rel="stylesheet" type="text/css">
</head>

<br><div class="publish">社内掲示板</div>

	<div class="header">
         <a href="logout" id="href" type="button">ログアウト</a>
     </div>

     <span><a href="newPublish" id="href" type="button">新規投稿</a></span>
      <br>
     <!--  総務部しか表示されない -->
     <c:if test="${loginUser.position_id == 1}">
        <br><a href="userManagement" id="href" type="button">ユーザー管理</a><br>
     </c:if><br>

    <!--  <div class="company">社内掲示板</div> -->


<body>
 		 <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                        <c:forEach items="${errorMessages}" var="message">
                            <c:out value="${message}" />
                        </c:forEach>
                </div>
                <c:remove var="errorMessages" scope="session"/>
      	   </c:if><br>


        <span class="welcome"> <c:out value="${loginUser.name}"></c:out>さん、ようこそ</span>
        <br>

<%-- 		<p class="form-area">
			 <c:if test="${ isShowMessageForm }">
			 	 <form action="newMessage" method="post">
					<textarea name="message" cols="100" rows="5"  class="tweet-box"></textarea> <br />
			 			 <input type="submit" value="投稿">
				 </form>
			</c:if>
		</p>
		 <br> --%>

		    <!-- 検索エリア -->
			<br><p class="searchCategory"><form action="./" method="get">カテゴリー
				<input type="search" name="searchCategory" id="searchCategory" placeholder="キーワードを入力"  value="${searchCategory}" ><br>
				<div class="search-area">
				期間<input type="date" name="firstDate" id="firstDate"  value="${firstDate}" />～
				<input type="date" name="finalDate" id="finalDate"  value="${finalDate}" />
				<input type="submit" value="検索"  id="submit_button"/></div>
			<!-- 	<input type="reset" value="リセット" /> -->
			</form>
		<br /><br>


	<!-- 投稿表示 --><br><br>
	<div class ="publishlist"><label for="publish">投稿一覧</label></div>
		<c:forEach items="${newPublishes}" var="newPublish">
		<div class="text">
			<p><div class="title"><br><p><label for="title" id="title">タイトル</label></p>
					<c:out value="${newPublish.title}"/>
				</div>
			<br />

			<p><span class="line-break1" ><c:out value="${newPublish.text}"></c:out></span></p>
			<br>
			   	<span class="category">カテゴリー<br>
    				<c:out value="${newPublish.category}" /></span><br><br>
			<br>
			<span class="name" >published by <c:out value="${newPublish.name}" /><br>
			<fmt:formatDate value="${newPublish.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></span><br>


			<!-- 投稿削除 -->
		<div class="button">
			<c:if test="${loginUser.id == newPublish.userid || loginUser.position_id == 2}">
				<form action="PublishDelete" method="post">
			 		<input type="hidden" name= "publish_id"  value="${newPublish.id}" />
					<input type="submit" value="上記の投稿を削除" onClick="return disp();" id="submit_button"/>
				</form><br>
			</c:if>
		</div>


		<!-- コメント表示 -->
		<div class="comment">
			<c:forEach items="${comments}" var="UserComment">
				<c:if test="${UserComment.publishId == newPublish.id}">
					<br><br><label for="comme">コメント</label><br><br>

					<span class="line-break"><c:out value="${UserComment.text}"/>
					</span>
					<span>commented by <c:out value= "${UserComment.name}" /></span><br>
					<span><fmt:formatDate value="${UserComment.created_date}" pattern="yyyy/MM/dd HH:mm:ss"/>
					</span>
				</c:if>

				<!-- コメント削除 -->
				 <c:if test="${loginUser.id == UserComment.userId}">
				 <c:if test="${UserComment.publishId == newPublish.id}">
					<div class= "CommentDelete">
						<form action="CommentDelete" method="post">
							 <input type="hidden" name= "comment_id"  value="${UserComment.id}" />
							 <input type="submit" value="削除" onClick="return disp1();" id="submit_button"/>
							 <br><br>
						</form>
					</div>
				</c:if>
				</c:if>
			 </c:forEach>
		</div>
		<!-- コメント投稿 -->
			<div class="form-area">
			<form action="comment" method="post">
				 <c:if test="${newPublish.id != inputUserComment.publishId}">
					<textarea name="comment" cols="25" rows="5" class="tweet-box" ></textarea><br />
		          	 	<input type="hidden" name= "publish_id"  value="${newPublish.id}" />
		          	 	<input type="hidden" name= "user_id"  value="${loginUser.id}" />
		         	 	<input type="submit" value="コメント" id="submit_button"/> <br />(500文字以内)
		    	 </c:if>

			</form>
			</div>

			<div class="form-area">
				<form action="comment" method="post">
					<c:if test="${newPublish.id == inputUserComment.publishId}">
						<textarea name="comment" cols="25" rows="5" class="tweet-box">${inputUserComment.text}</textarea><br />
		         		   <input type="hidden" name= "publish_id"  value="${newPublish.id}" />
		          		   <input type="hidden" name= "user_id"  value="${loginUser.id}" />
		          		   <input type="submit" value="コメント" id="submit_button"/> <br />(500文字以内)
		          			  <c:remove var="inputUserComment" scope="session"/>
		     	   </c:if>
				</form>
			</div></div>
		 </c:forEach>

		<br>
	   <a href="./" id="href">上に戻る</a>
            <div class="copyright"> Copyright(c)Kyosuke Gimba</div>

<script type="text/javascript">
<!--
function disp(){
	if(window.confirm('本当にこの投稿を削除しますか？')){
		return true;
	}else{
		window.alert('キャンセルされました');
		return false;
	}
}
function disp1(){
	if(window.confirm('本当にこのコメントを削除しますか？')){
		return true;
	}else{
		window.alert('キャンセルされました');
		return false;
	}
}
// -->
</script>
    </body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>社内掲示板</title>
</head>
<head>
    <link href="./css/login.css" rel="stylesheet" type="text/css">
</head>
<body>
</body>

			<br>
            <div class="title">社内掲示板</div>

             <c:if test="${ not empty errorMessages }">

                <div class="errorMessages">
                        <c:forEach items="${errorMessages}" var="message">
                           <br> <c:out value="${message}"/>
                        </c:forEach>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <div class="main-contents">

            <form action="login" method="post">
                <label for="login_id">ログインID</label><br />
                <input name="login_id" id="login_id" value="${loginuser.login_id}"/>

               <p> <label for="password">パスワード</label><br />
                <input name="password" type="password" id="password"/> <br /></p>

                <input type="submit" value="ログイン"  id="submit_button" /> <br /><br />
            </form>
            <div class="copyright"> Copyright(c)Kyosuke Gimba</div>
        </div>

</html>

WebContent/publish.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>新規投稿</title>
</head>
<head>
    <link href="./css/publish.css" rel="stylesheet" type="text/css">
</head>
<br>
	<div class="newPublish">新規投稿</div>

	<div class="header">
		<a href="logout" id="href">ログアウト</a>
	</div>


<a href="./" id="href">ホームに戻る</a><br>


		     <c:if test="${empty errorMessages }"><br></c:if>

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                	<ul style = "display: inline-block; text-align:left">
                        <c:forEach items="${errorMessages}" var="message">
                            <c:out value="${message}" /><br>
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>


     <div class="main-contents">
			<form action="newPublish" method="post">
                <label for="title">タイトル</label> (30文字以下)<br />
               <span> <input name="title" id="title" value="${newPublish.title}"/></span> <br />

                <label for="text">本文</label>（1000文字以下）<br />

                <span><textarea name="text" cols="100" rows="5" class="tweet-box">${newPublish.text}</textarea></span>
               <br />

                <label for="category">カテゴリー</label>（10文字以下）<br />
               <span> <input name="category" type="text" id="category" value="${newPublish.category}"/></span>
                <br />
                <input type="submit" value="投稿" id="submit_button"/><br />
            </form>
        </div>

            <div class="copyright"> Copyright(c)Kyosuke Gimba</div>

</html>